### PR TITLE
Apply support for large PROPFINDS to 3.2.

### PR DESCRIPTION
**Pull request by rayward**
Takes Petr's changes from the 3.2.0.1 tag on this fork and (from this PR - https://github.com/sabre-io/dav/pull/898 - which wasn't accepted) and applies them to the 3.2 branch. 

I originally tried to apply this to the most recent tag of 3.2 (3.2.2), but it had many test failures which required the most recent commits from the 3.2 working branch.

Also applied a couple of unit test fixes.

This depends on bigcommerce-labs/sabre-http#2.

### CODE REVIEW

**Comment by rayward** [comment]
I can't get travis/composer/github to play well with a custom repository due to API limits.

Ran the tests locally.
```
ray.ward@syd-mbp-ward1:/Projects/sabre-dav (3.2-bc)$ bin/phpunit --configuration tests/phpunit.xml.dist tests/
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

.............................................................   61 / 1584 (  3%)
.............................................................  122 / 1584 (  7%)
.............................................................  183 / 1584 ( 11%)
.............................................................  244 / 1584 ( 15%)
.............................................................  305 / 1584 ( 19%)
.............................................................  366 / 1584 ( 23%)
.............................................................  427 / 1584 ( 26%)
.............................................................  488 / 1584 ( 30%)
.............................................................  549 / 1584 ( 34%)
.............................................................  610 / 1584 ( 38%)
.............................................................  671 / 1584 ( 42%)
.............................................................  732 / 1584 ( 46%)
.............................................................  793 / 1584 ( 50%)
.............................................................  854 / 1584 ( 53%)
.............................................................  915 / 1584 ( 57%)
.............................................................  976 / 1584 ( 61%)
............................................................. 1037 / 1584 ( 65%)
............................................................. 1098 / 1584 ( 69%)
............................................................. 1159 / 1584 ( 73%)
............................................................. 1220 / 1584 ( 77%)
............................................................. 1281 / 1584 ( 80%)
............................................................. 1342 / 1584 ( 84%)
............................................................. 1403 / 1584 ( 88%)
............................................................. 1464 / 1584 ( 92%)
............................................................. 1525 / 1584 ( 96%)
...........................................................   1584 / 1584 (100%)

Time: 16.88 seconds, Memory: 56.00MB

OK (1584 tests, 3288 assertions)
```

**Comment by rayward** [comment]
ping @philipmuir @gwilym

**Review by xyzjace — APPROVED** [review]

**Comment by xyzjace** [comment]
I wonder if 
```
Failed to clone the git@github.com:bigcommerce-labs/sabre-http.git repository, try running in interactive mode so that you can enter your GitHub credentials
```
is having issues because Composer isn't using the Travis credentials. to clone the repo. We can't add the creds to the Travis build since this is a fork of a public repo.

Is there a way to tell composer where to source git creds from?

**Comment by rayward** [comment]
Both repos are public and travis gets rate limited by github. 

We can't add an SSH key in the Travis settings for public repos :(

I've tried a few variations of using https/git protocol and various composer flags but it doesn't seem to play well as soon as we use a custom repository for the library.

**Pull request merged**
